version: '2'
services:
    bixdemo-app:
        image: bixdemo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://bixdemo-mysql:3306/bixdemo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bixdemo-mysql:
        extends:
            file: mysql.yml
            service: bixdemo-mysql
